# Order Analysis with NumPy

**Project objective**  
This notebook analyzes a small order dataset using **NumPy**. The analysis calculates revenue, costs, margins, delivery performance, customer satisfaction, and a synthetic performance indicator called `quality_score`.

---

## Analysis structure

1. Dataset creation and inspection  
2. Extraction of the main variables  
3. Revenue, cost, and margin calculation  
4. Percentage margin analysis  
5. Order segmentation by delivery speed  
6. Construction of the `quality_score`  
7. Order classification  
8. Final report


## 1. Library import and dataset creation

In this section, the **NumPy** library is imported and the starting dataset is created.  
Each row represents one order, while each column contains a specific variable.

| Column | Variable | Meaning |
|---:|---|---|
| 0 | `quantita` | Number of units purchased |
| 1 | `prezzo_unitario` | Selling price per unit |
| 2 | `costo_unitario` | Unit cost |
| 3 | `giorni_consegna` | Order delivery time |
| 4 | `soddisfazione` | Customer satisfaction score |


In [1]:
import numpy as np

dataset = np.array([
    [2, 50, 30, 3, 5],
    [1, 120, 80, 5, 4],
    [3, 40, 22, 2, 5],
    [5, 25, 15, 7, 3],
    [2, 200, 140, 4, 4],
    [1, 300, 210, 6, 3],
    [4, 35, 20, 2, 5],
    [2, 75, 45, 3, 4],
    [6, 20, 12, 8, 2],
    [1, 500, 350, 5, 5],
    [3, 60, 35, 4, 4],
    [2, 90, 55, 6, 3],
    [4, 45, 25, 3, 5],
    [1, 250, 180, 7, 2],
    [5, 30, 18, 2, 4],
    [2, 150, 100, 4, 5],
    [3, 80, 50, 5, 3],
    [1, 700, 500, 6, 4],
    [2, 110, 70, 3, 5],
    [4, 55, 32, 4, 4],
    [6, 18, 10, 9, 2],
    [3, 95, 60, 5, 3],
    [2, 180, 120, 4, 5],
    [1, 400, 280, 6, 4],
    [5, 22, 13, 7, 3],
    [2, 130, 85, 3, 5],
    [3, 70, 42, 4, 4],
    [4, 38, 21, 2, 5],
    [1, 600, 430, 8, 2],
    [2, 160, 105, 5, 4]
])

## 2. Preliminary dataset structure check

Before starting the analysis, it is useful to inspect a few technical characteristics of the array:

- number of dimensions;
- dataset shape;
- total number of elements;
- data type stored in the array.


In [2]:
print(dataset.ndim)
print(dataset.shape)
print(dataset.size)
print(dataset.dtype)

2
(30, 5)
150
int64


## 3. Variable extraction

The dataset columns are separated into one-dimensional arrays.  
This step makes it easier to work with individual variables without repeatedly referencing column indexes.


In [3]:
quantita = dataset[:,0]
prezzo_unitario = dataset[:,1]
costo_unitario = dataset[:,2]
giorni_consegna = dataset[:,3]
soddisfazione = dataset[:,4]

### Extracted variable check

Printing the arrays allows us to verify that each column has been selected correctly.


In [4]:
print(quantita)
print(prezzo_unitario)
print(costo_unitario)
print(giorni_consegna)
print(soddisfazione)

[2 1 3 5 2 1 4 2 6 1 3 2 4 1 5 2 3 1 2 4 6 3 2 1 5 2 3 4 1 2]
[ 50 120  40  25 200 300  35  75  20 500  60  90  45 250  30 150  80 700
 110  55  18  95 180 400  22 130  70  38 600 160]
[ 30  80  22  15 140 210  20  45  12 350  35  55  25 180  18 100  50 500
  70  32  10  60 120 280  13  85  42  21 430 105]
[3 5 2 7 4 6 2 3 8 5 4 6 3 7 2 4 5 6 3 4 9 5 4 6 7 3 4 2 8 5]
[5 4 5 3 4 3 5 4 2 5 4 3 5 2 4 5 3 4 5 4 2 3 5 4 3 5 4 5 2 4]


## 4. Revenue, cost, and margin calculation per order

For each order, three key economic indicators are calculated:

- **revenue** = unit price × quantity;
- **cost** = unit cost × quantity;
- **margin** = revenue − cost.


In [5]:
ricavo = prezzo_unitario * quantita
costo = costo_unitario * quantita
margine = ricavo - costo

### Economic values per individual order

This cell returns the arrays related to revenue, costs, and margins calculated for each transaction.


In [6]:
print(f"Revenue for each individual transaction: {ricavo}")
print(f"Cost for each individual transaction: {costo}")
print(f"Margin for each individual transaction: {margine}")

Revenue for each individual transaction: [100 120 120 125 400 300 140 150 120 500 180 180 180 250 150 300 240 700
 220 220 108 285 360 400 110 260 210 152 600 320]
Cost for each individual transaction: [ 60  80  66  75 280 210  80  90  72 350 105 110 100 180  90 200 150 500
 140 128  60 180 240 280  65 170 126  84 430 210]
Margin for each individual transaction: [ 40  40  54  50 120  90  60  60  48 150  75  70  80  70  60 100  90 200
  80  92  48 105 120 120  45  90  84  68 170 110]


## 5. Aggregate economic indicators

This section calculates the main aggregate metrics of the dataset:

- total revenue;
- total cost;
- total margin;
- average margin per order;
- order with the highest margin;
- order with the lowest margin.


In [7]:
ricavo_totale = np.sum(ricavo)
costo_totale = np.sum(costo)
margine_totale = np.sum(margine)
margine_medio_ordine = np.mean(margine)
ordine_migliore = np.max(margine)
ordine_peggiore = np.min(margine)

### Aggregate indicator output

These values provide a first overall view of the economic performance of the orders.


In [8]:
print(ricavo_totale)
print(costo_totale)
print(margine_totale)
print(margine_medio_ordine)
print(ordine_migliore)
print(ordine_peggiore)

7500
4911
2589
86.3
200
40


## 6. Percentage margin

Percentage margin is used to evaluate the relative profitability of each order, regardless of its absolute value.

The formula used is:

$$
\text{Percentage margin} = \frac{\text{Margin}}{\text{Revenue}} \times 100
$$


In [9]:
margine_percentuale = np.round(margine / ricavo * 100,2)
margine_percentuale_medio = np.round(np.mean(margine_percentuale),2)

### Percentage margin output

The first output shows the percentage margin of each order.  
The second output shows the average percentage margin of the dataset.


In [10]:
print(margine_percentuale)
print(margine_percentuale_medio)

[40.   33.33 45.   40.   30.   30.   42.86 40.   40.   30.   41.67 38.89
 44.44 28.   40.   33.33 37.5  28.57 36.36 41.82 44.44 36.84 33.33 30.
 40.91 34.62 40.   44.74 28.33 34.38]
36.98


## 7. Identification of high-margin orders

A Boolean mask is created to select orders with a percentage margin greater than or equal to 40%.

This step introduces a core NumPy concept: **filtering through conditions**.


In [11]:
maschera = margine_percentuale >= 40
margine_alto = margine_percentuale[maschera]

### Margins above the threshold

This output returns only the percentage margins that satisfy the defined condition.


In [12]:
print(margine_alto)

[40.   45.   40.   42.86 40.   40.   41.67 44.44 40.   41.82 44.44 40.91
 40.   44.74]


### High-margin orders

The same mask is applied to the original dataset to retrieve the complete rows of high-margin orders.


In [13]:
ordini_margine_alto = dataset[maschera]
print(ordini_margine_alto)

[[ 2 50 30  3  5]
 [ 3 40 22  2  5]
 [ 5 25 15  7  3]
 [ 4 35 20  2  5]
 [ 2 75 45  3  4]
 [ 6 20 12  8  2]
 [ 3 60 35  4  4]
 [ 4 45 25  3  5]
 [ 5 30 18  2  4]
 [ 4 55 32  4  4]
 [ 6 18 10  9  2]
 [ 5 22 13  7  3]
 [ 3 70 42  4  4]
 [ 4 38 21  2  5]]


## 8. High-margin orders with fast delivery

Here, a double condition is applied:

- percentage margin greater than or equal to 40%;
- delivery within 3 days.

The goal is to identify the best orders from both an economic and operational perspective.


In [14]:
margine_consegna = (margine_percentuale >= 40) & (giorni_consegna <= 3)
top_ordini = dataset[margine_consegna]

### Best operational orders output

These orders combine solid profitability with fast delivery times.


In [15]:
print(top_ordini)

[[ 2 50 30  3  5]
 [ 3 40 22  2  5]
 [ 4 35 20  2  5]
 [ 2 75 45  3  4]
 [ 4 45 25  3  5]
 [ 5 30 18  2  4]
 [ 4 38 21  2  5]]


## 9. Percentage incidence of top orders

This section calculates how much the `top_ordini` subset weighs compared to the total number of orders in the dataset.


In [16]:
numero_ordini = dataset.shape[0]
num_top_ordini = top_ordini.shape[0]
percentuale_top_ordini = np.round(num_top_ordini / numero_ordini * 100,2)

### Number and percentage of top orders

The percentage helps determine whether the best orders are isolated cases or a significant part of the dataset.


In [17]:
print(numero_ordini)
print(num_top_ordini)
print(percentuale_top_ordini)

30
7
23.33


## 10. Delivery speed segmentation

Orders are divided into two groups:

- **fast delivery**: delivery within 3 days;
- **slow delivery**: delivery after more than 5 days.

This segmentation makes it possible to compare economic performance and customer satisfaction across two distinct operational categories.


In [18]:
consegna_veloce = giorni_consegna <= 3
consegna_lenta = giorni_consegna > 5
ordini_consegna_veloce = dataset[consegna_veloce]
ordini_consegna_lenta = dataset[consegna_lenta]

### Fast and slow order output

The two outputs allow us to directly inspect the rows belonging to each group.


In [19]:
print(ordini_consegna_veloce)
print(ordini_consegna_lenta)

[[  2  50  30   3   5]
 [  3  40  22   2   5]
 [  4  35  20   2   5]
 [  2  75  45   3   4]
 [  4  45  25   3   5]
 [  5  30  18   2   4]
 [  2 110  70   3   5]
 [  2 130  85   3   5]
 [  4  38  21   2   5]]
[[  5  25  15   7   3]
 [  1 300 210   6   3]
 [  6  20  12   8   2]
 [  2  90  55   6   3]
 [  1 250 180   7   2]
 [  1 700 500   6   4]
 [  6  18  10   9   2]
 [  1 400 280   6   4]
 [  5  22  13   7   3]
 [  1 600 430   8   2]]


## 11. Customer satisfaction comparison

This section compares overall average satisfaction with the average satisfaction of fast-delivery and slow-delivery orders.

The objective is to check whether faster delivery appears to be associated with higher customer satisfaction.


In [20]:
soddisfazione_media = np.round(np.mean(soddisfazione),2)
soddisfazione_veloci = np.round(np.mean(ordini_consegna_veloce[:,4]),2)
soddisfazione_lenta = np.round(np.mean(ordini_consegna_lenta[:,4],),2)

### Average satisfaction output

The three outputs show, respectively:

1. overall average satisfaction;
2. average satisfaction for fast-delivery orders;
3. average satisfaction for slow-delivery orders.


In [21]:
print(soddisfazione_media)
print(soddisfazione_veloci)
print(soddisfazione_lenta)

3.87
4.78
2.8


## 12. Economic comparison between fast and slow orders

In addition to customer satisfaction, average revenue and average margin are compared across the two groups.

This helps understand whether faster-delivered orders are also more attractive from an economic perspective.


In [22]:
ricavo_medio_veloci = np.round(np.mean(ricavo[consegna_veloce]),2)
ricavo_medio_lenti = np.round(np.mean(ricavo[consegna_lenta]),2)
margine_medio_veloci = np.round(np.mean(margine[consegna_veloce]),2)
margine_medio_lenti = np.round(np.mean(margine[consegna_lenta]),2)

### Economic comparison output

The outputs show average revenue and average margin for fast and slow orders.


In [23]:
print(ricavo_medio_veloci)
print(ricavo_medio_lenti)
print(margine_medio_veloci)
print(margine_medio_lenti)

163.56
289.3
65.78
91.1


## 13. Average percentage margin comparison

The comparison is completed by analyzing the average percentage margin for fast and slow orders.

This metric is useful because it normalizes profitability relative to the order value.


In [24]:
margine_percentuale_medio_veloci = np.round(np.mean(margine_percentuale[consegna_veloce]),2)
margine_percentuale_medio_lenti = np.round(np.mean(margine_percentuale[consegna_lenta]),2)

### Average percentage margin by segment

The two outputs compare the relative profitability of fast and slow orders.


In [25]:
print(margine_percentuale_medio_veloci)
print(margine_percentuale_medio_lenti)

40.89
34.91


## 14. Quality Score construction

The `quality_score` is a synthetic indicator created to evaluate each order by combining three dimensions:

- percentage margin;
- customer satisfaction;
- delivery days.

The formula rewards profitable orders with high customer satisfaction and penalizes longer delivery times.

$$
\text{Quality Score} = \text{Percentage margin} + (\text{Satisfaction} \times 10) - (\text{Delivery days} \times 2)
$$


In [26]:
quality_score = np.round(margine_percentuale + soddisfazione * 10 - giorni_consegna * 2,2)

### Quality Score descriptive indicators

The average, maximum, and minimum values of the `quality_score` are calculated.


In [27]:
quality_score_medio = np.round(np.mean(quality_score),2)
quality_score_massimo = np.round(np.max(quality_score),2)
quality_score_minimo = np.round(np.min(quality_score),2)

### Quality Score output

The first output shows the score for each order.  
The following outputs show the average, maximum, and minimum values.


In [28]:
print(quality_score)
print(quality_score_medio)
print(quality_score_massimo)
print(quality_score_minimo)

[84.   63.33 91.   56.   62.   48.   88.86 74.   44.   70.   73.67 56.89
 88.44 34.   76.   75.33 57.5  56.57 80.36 73.82 46.44 56.84 75.33 58.
 56.91 78.62 72.   90.74 32.33 64.38]
66.18
91.0
32.33


## 15. Selection of high Quality Score orders

Orders with a `quality_score` greater than or equal to 80 are selected.

This threshold identifies the best orders according to the synthetic criterion defined above.


In [29]:
maschera_qualità = quality_score >= 80
ordini_migliori_quality = dataset[maschera_qualità]
quality_alti = quality_score[maschera_qualità]

### Best orders by Quality Score

The first output shows the dataset rows.  
The second output shows the related scores.


In [30]:
print(ordini_migliori_quality)
print(quality_alti)

[[  2  50  30   3   5]
 [  3  40  22   2   5]
 [  4  35  20   2   5]
 [  4  45  25   3   5]
 [  2 110  70   3   5]
 [  4  38  21   2   5]]
[84.   91.   88.86 88.44 80.36 90.74]


## 16. Best order according to the Quality Score

Using `np.argmax()`, the index of the order with the highest score is identified.

> **Note:** from this point onward, the variable `ordine_migliore` refers to the best order according to the `quality_score`, not to the absolute economic margin calculated in the first sections.


In [31]:
indice_migliore = np.argmax(quality_score)
ordine_migliore = dataset[indice_migliore]
quality_migliore = quality_score[indice_migliore]

### Best order output

The best order and its corresponding `quality_score` are printed.


In [32]:
print(ordine_migliore)
print(quality_migliore)

[ 3 40 22  2  5]
91.0


## 17. Worst order according to the Quality Score

Using `np.argmin()`, the index of the order with the lowest score is identified.


In [33]:
indice_peggiore = np.argmin(quality_score)
ordine_peggiore = dataset[indice_peggiore]
quality_peggiore = quality_score[indice_peggiore]

### Worst order output

The worst order and its corresponding `quality_score` are printed.


In [34]:
print(ordine_peggiore)
print(quality_peggiore)

[  1 600 430   8   2]
32.33


## 18. Qualitative order classification

Orders are classified into three categories:

| Class | Condition |
|---|---|
| `Excellent` | `quality_score >= 80` |
| `Good` | `quality_score >= 60` and below 80 |
| `Critical` | `quality_score < 60` |

The `np.where()` function makes it possible to create a vectorized conditional classification.


In [35]:
classe_quality = np.where(quality_score >= 80, "Excellent",
                 np.where(quality_score >= 60, "Good", "Critical"))
print(classe_quality)

['Excellent' 'Good' 'Excellent' 'Critical' 'Good' 'Critical' 'Excellent'
 'Good' 'Critical' 'Good' 'Good' 'Critical' 'Excellent' 'Critical' 'Good'
 'Good' 'Critical' 'Critical' 'Excellent' 'Good' 'Critical' 'Critical'
 'Good' 'Critical' 'Critical' 'Good' 'Good' 'Excellent' 'Critical' 'Good']


## 19. Count of qualitative classes

The number of orders belonging to each category is calculated.


In [36]:
ordini_eccellenti = np.sum(classe_quality == "Excellent")
ordini_buoni = np.sum(classe_quality == "Good")
ordini_critici = np.sum(classe_quality == "Critical")

### Class count output

These outputs show how many orders are classified as excellent, good, or critical.


In [37]:
print(ordini_eccellenti)
print(ordini_buoni)
print(ordini_critici)

6
12
12


## 20. Percentage distribution of classes

Using `np.unique()`, the existing classes and their respective occurrence counts are retrieved.  
Then, the percentage weight of each class over the total number of orders is calculated.


In [38]:
classi, conteggi = np.unique(classe_quality, return_counts=True)
percentuali_ordini = np.round(conteggi / numero_ordini * 100,2)
print(classi)
print(conteggi)
print(percentuali_ordini)

['Critical' 'Excellent' 'Good']
[12  6 12]
[40. 20. 40.]


## 21. Class summary table

Counts and percentages are combined into a single structure using `np.column_stack()`.


In [39]:
riepilogativo = np.column_stack((conteggi, percentuali_ordini))
print(riepilogativo)

[[12. 40.]
 [ 6. 20.]
 [12. 40.]]


## 22. Sorting classes by frequency

Classes are sorted by the number of orders, from the most frequent to the least frequent.

This step makes the qualitative distribution easier to read.


In [40]:
indici_ordinati = np.argsort(conteggi)[::-1]
classi_ordinati = classi[indici_ordinati]
conteggi_ordinati = conteggi[indici_ordinati]
percentuali_ordinati = percentuali_ordini[indici_ordinati]

### Sorted class output

The ordered indexes, classes, counts, and percentages are printed.


In [41]:
print(indici_ordinati)
print(classi_ordinati)
print(conteggi_ordinati)
print(percentuali_ordinati)

[2 0 1]
['Good' 'Critical' 'Excellent']
[12 12  6]
[40. 40. 20.]


## 23. Final report

The last section summarizes the main results of the analysis in a readable format.

The report includes:

- total revenue, costs, and margins;
- average percentage margin;
- average satisfaction;
- number of excellent and critical orders;
- best and worst order according to the `quality_score`.


In [42]:
print("FINAL ORDER ANALYSIS REPORT")
print("-----------------------------")

print(f"Total revenue: {ricavo_totale}")
print(f"Total cost: {costo_totale}")
print(f"Total margin: {margine_totale}")
print(f"Average percentage margin: {margine_percentuale_medio}")
print(f"Average satisfaction: {soddisfazione_media}")

print(f"Excellent orders: {ordini_eccellenti}")
print(f"Critical orders: {ordini_critici}")

print(f"Best order: {ordine_migliore}")
print(f"Best order quality score: {quality_migliore}")

print(f"Worst order: {ordine_peggiore}")
print(f"Worst order quality score: {quality_peggiore}")

FINAL ORDER ANALYSIS REPORT
-----------------------------
Total revenue: 7500
Total cost: 4911
Total margin: 2589
Average percentage margin: 36.98
Average satisfaction: 3.87
Excellent orders: 6
Critical orders: 12
Best order: [ 3 40 22  2  5]
Best order quality score: 91.0
Worst order: [  1 600 430   8   2]
Worst order quality score: 32.33


---

## Final observations

The project effectively demonstrates the use of NumPy to:

- create and manipulate arrays;
- select columns and rows;
- build Boolean masks;
- calculate aggregate indicators;
- classify observations through conditions;
- build a concise final report.