# Analisi ordini con NumPy

**Obiettivo del progetto**  
Questo notebook analizza un dataset di ordini utilizzando **NumPy**. L'analisi calcola ricavi, costi, margini, performance di consegna, soddisfazione cliente e un indicatore sintetico chiamato `quality_score`.

---

## Struttura dell'analisi

1. Creazione e lettura del dataset  
2. Separazione delle variabili principali  
3. Calcolo di ricavi, costi e margini  
4. Analisi dei margini percentuali  
5. Segmentazione degli ordini in base alla consegna  
6. Costruzione del `quality_score`  
7. Classificazione degli ordini  
8. Report finale


## 1. Importazione libreria e creazione del dataset

In questa sezione viene importata la libreria **NumPy** e viene costruito il dataset di partenza.  
Ogni riga rappresenta un ordine, mentre ogni colonna contiene una variabile specifica.

| Colonna | Variabile | Significato |
|---:|---|---|
| 0 | `quantita` | Numero di unità acquistate |
| 1 | `prezzo_unitario` | Prezzo di vendita per unità |
| 2 | `costo_unitario` | Costo sostenuto per unità |
| 3 | `giorni_consegna` | Tempo di consegna dell'ordine |
| 4 | `soddisfazione` | Valutazione del cliente |


In [2]:
import numpy as np

dataset = np.array([
    [2, 50, 30, 3, 5],
    [1, 120, 80, 5, 4],
    [3, 40, 22, 2, 5],
    [5, 25, 15, 7, 3],
    [2, 200, 140, 4, 4],
    [1, 300, 210, 6, 3],
    [4, 35, 20, 2, 5],
    [2, 75, 45, 3, 4],
    [6, 20, 12, 8, 2],
    [1, 500, 350, 5, 5],
    [3, 60, 35, 4, 4],
    [2, 90, 55, 6, 3],
    [4, 45, 25, 3, 5],
    [1, 250, 180, 7, 2],
    [5, 30, 18, 2, 4],
    [2, 150, 100, 4, 5],
    [3, 80, 50, 5, 3],
    [1, 700, 500, 6, 4],
    [2, 110, 70, 3, 5],
    [4, 55, 32, 4, 4],
    [6, 18, 10, 9, 2],
    [3, 95, 60, 5, 3],
    [2, 180, 120, 4, 5],
    [1, 400, 280, 6, 4],
    [5, 22, 13, 7, 3],
    [2, 130, 85, 3, 5],
    [3, 70, 42, 4, 4],
    [4, 38, 21, 2, 5],
    [1, 600, 430, 8, 2],
    [2, 160, 105, 5, 4]
])

## 2. Controllo preliminare della struttura del dataset

Prima di procedere con l'analisi, è utile verificare alcune caratteristiche tecniche dell'array:

- numero di dimensioni;
- forma del dataset;
- numero totale di elementi;
- tipo di dato contenuto nell'array.


In [3]:
print(dataset.ndim)
print(dataset.shape)
print(dataset.size)
print(dataset.dtype)

2
(30, 5)
150
int64


## 3. Estrazione delle variabili

Le colonne del dataset vengono separate in array monodimensionali.  
Questo passaggio rende più semplice lavorare con le singole variabili senza dover richiamare continuamente gli indici delle colonne.


In [4]:
quantita = dataset[:,0]
prezzo_unitario = dataset[:,1]
costo_unitario = dataset[:,2]
giorni_consegna = dataset[:,3]
soddisfazione = dataset[:,4]

### Verifica delle variabili estratte

La stampa degli array permette di controllare che ogni colonna sia stata selezionata correttamente.


In [5]:
print(quantita)
print(prezzo_unitario)
print(costo_unitario)
print(giorni_consegna)
print(soddisfazione)

[2 1 3 5 2 1 4 2 6 1 3 2 4 1 5 2 3 1 2 4 6 3 2 1 5 2 3 4 1 2]
[ 50 120  40  25 200 300  35  75  20 500  60  90  45 250  30 150  80 700
 110  55  18  95 180 400  22 130  70  38 600 160]
[ 30  80  22  15 140 210  20  45  12 350  35  55  25 180  18 100  50 500
  70  32  10  60 120 280  13  85  42  21 430 105]
[3 5 2 7 4 6 2 3 8 5 4 6 3 7 2 4 5 6 3 4 9 5 4 6 7 3 4 2 8 5]
[5 4 5 3 4 3 5 4 2 5 4 3 5 2 4 5 3 4 5 4 2 3 5 4 3 5 4 5 2 4]


## 4. Calcolo di ricavo, costo e margine per ordine

Per ogni ordine vengono calcolati tre indicatori economici fondamentali:

- **ricavo** = prezzo unitario × quantità;
- **costo** = costo unitario × quantità;
- **margine** = ricavo − costo.


In [6]:
ricavo = prezzo_unitario * quantita
costo = costo_unitario * quantita
margine = ricavo - costo

### Output dei valori economici per singolo ordine

Questa cella restituisce gli array relativi a ricavi, costi e margini calcolati per ciascuna transazione.


In [7]:
print(f"il ricavo per ogni singola transazione è {ricavo}")
print(f"il costo per ogni singola transazione è pari a {costo}")
print(f"il margine per ogni singola transazione è pari a {margine}")

il ricavo per ogni singola transazione è [100 120 120 125 400 300 140 150 120 500 180 180 180 250 150 300 240 700
 220 220 108 285 360 400 110 260 210 152 600 320]
il costo per ogni singola transazione è pari a [ 60  80  66  75 280 210  80  90  72 350 105 110 100 180  90 200 150 500
 140 128  60 180 240 280  65 170 126  84 430 210]
il margine per ogni singola transazione è pari a [ 40  40  54  50 120  90  60  60  48 150  75  70  80  70  60 100  90 200
  80  92  48 105 120 120  45  90  84  68 170 110]


## 5. Indicatori economici aggregati

In questa sezione vengono calcolate le principali metriche aggregate del dataset:

- ricavo totale;
- costo totale;
- margine totale;
- margine medio per ordine;
- ordine con margine massimo;
- ordine con margine minimo.


In [8]:
ricavo_totale = np.sum(ricavo)
costo_totale = np.sum(costo)
margine_totale = np.sum(margine)
margine_medio_ordine = np.mean(margine)
ordine_migliore = np.max(margine)
ordine_peggiore = np.min(margine)

### Stampa degli indicatori aggregati

Questi valori offrono una prima lettura complessiva della performance economica degli ordini.


In [9]:
print(ricavo_totale)
print(costo_totale)
print(margine_totale)
print(margine_medio_ordine)
print(ordine_migliore)
print(ordine_peggiore)

7500
4911
2589
86.3
200
40


## 6. Margine percentuale

Il margine percentuale consente di valutare la redditività relativa di ciascun ordine, indipendentemente dal suo valore assoluto.

In [10]:
margine_percentuale = np.round(margine / ricavo * 100,2)
margine_percentuale_medio = np.round(np.mean(margine_percentuale),2)

### Stampa dei margini percentuali

La prima stampa mostra il margine percentuale di ogni ordine.  
La seconda stampa mostra il margine percentuale medio del dataset.


In [11]:
print(margine_percentuale)
print(margine_percentuale_medio)

[40.   33.33 45.   40.   30.   30.   42.86 40.   40.   30.   41.67 38.89
 44.44 28.   40.   33.33 37.5  28.57 36.36 41.82 44.44 36.84 33.33 30.
 40.91 34.62 40.   44.74 28.33 34.38]
36.98


## 7. Identificazione degli ordini ad alto margine

Viene creata una maschera booleana per selezionare gli ordini con margine percentuale maggiore o uguale al 40%.

Questo passaggio introduce un concetto centrale di NumPy: il **filtraggio tramite condizioni**.


In [12]:
maschera = margine_percentuale >= 40
margine_alto = margine_percentuale[maschera]

### Margini superiori alla soglia

Questa stampa restituisce solo i margini percentuali che rispettano la condizione impostata.


In [13]:
print(margine_alto)

[40.   45.   40.   42.86 40.   40.   41.67 44.44 40.   41.82 44.44 40.91
 40.   44.74]


### Ordini con margine alto

La stessa maschera viene applicata al dataset originale per recuperare le righe complete degli ordini ad alto margine.


In [14]:
ordini_margine_alto = dataset[maschera]
print(ordini_margine_alto)

[[ 2 50 30  3  5]
 [ 3 40 22  2  5]
 [ 5 25 15  7  3]
 [ 4 35 20  2  5]
 [ 2 75 45  3  4]
 [ 6 20 12  8  2]
 [ 3 60 35  4  4]
 [ 4 45 25  3  5]
 [ 5 30 18  2  4]
 [ 4 55 32  4  4]
 [ 6 18 10  9  2]
 [ 5 22 13  7  3]
 [ 3 70 42  4  4]
 [ 4 38 21  2  5]]


## 8. Ordini con margine alto e consegna veloce

Qui viene applicata una doppia condizione:

- margine percentuale almeno pari al 40%;
- consegna entro 3 giorni.

L'obiettivo è individuare gli ordini migliori sia dal punto di vista economico sia dal punto di vista operativo.


In [15]:
margine_consegna = (margine_percentuale >= 40) & (giorni_consegna <= 3)
top_ordini = dataset[margine_consegna]

### Stampa dei migliori ordini operativi

Questi ordini combinano buona redditività e tempi di consegna rapidi.


In [16]:
print(top_ordini)

[[ 2 50 30  3  5]
 [ 3 40 22  2  5]
 [ 4 35 20  2  5]
 [ 2 75 45  3  4]
 [ 4 45 25  3  5]
 [ 5 30 18  2  4]
 [ 4 38 21  2  5]]


## 9. Incidenza percentuale dei top ordini

Questa sezione calcola quanto pesano i `top_ordini` sul totale degli ordini presenti nel dataset.


In [17]:
numero_ordini = dataset.shape[0]
num_top_ordini = top_ordini.shape[0]
percentuale_top_ordini = np.round(num_top_ordini / numero_ordini * 100,2)

### Numero e percentuale di top ordini

La percentuale aiuta a capire se gli ordini migliori sono casi isolati oppure una componente significativa del dataset.


In [18]:
print(numero_ordini)
print(num_top_ordini)
print(percentuale_top_ordini)

30
7
23.33


## 10. Segmentazione per velocità di consegna

Gli ordini vengono divisi in due gruppi:

- **consegna veloce**: consegna entro 3 giorni;
- **consegna lenta**: consegna oltre 5 giorni.

Questa segmentazione permette di confrontare performance economiche e soddisfazione cliente tra due categorie operative distinte.


In [19]:
consegna_veloce = giorni_consegna <= 3
consegna_lenta = giorni_consegna > 5
ordini_consegna_veloce = dataset[consegna_veloce]
ordini_consegna_lenta = dataset[consegna_lenta]

### Stampa degli ordini veloci e lenti

Le due stampe permettono di osservare direttamente le righe appartenenti ai due gruppi.


In [20]:
print(ordini_consegna_veloce)
print(ordini_consegna_lenta)

[[  2  50  30   3   5]
 [  3  40  22   2   5]
 [  4  35  20   2   5]
 [  2  75  45   3   4]
 [  4  45  25   3   5]
 [  5  30  18   2   4]
 [  2 110  70   3   5]
 [  2 130  85   3   5]
 [  4  38  21   2   5]]
[[  5  25  15   7   3]
 [  1 300 210   6   3]
 [  6  20  12   8   2]
 [  2  90  55   6   3]
 [  1 250 180   7   2]
 [  1 700 500   6   4]
 [  6  18  10   9   2]
 [  1 400 280   6   4]
 [  5  22  13   7   3]
 [  1 600 430   8   2]]


## 11. Confronto della soddisfazione cliente

In questa sezione viene confrontata la soddisfazione media generale con quella degli ordini veloci e degli ordini lenti.

Questo passaggio serve a verificare se la rapidità di consegna sembra associarsi a una soddisfazione più alta.


In [21]:
soddisfazione_media = np.round(np.mean(soddisfazione),2)
soddisfazione_veloci = np.round(np.mean(ordini_consegna_veloce[:,4]),2)
soddisfazione_lenta = np.round(np.mean(ordini_consegna_lenta[:,4],),2)

### Output della soddisfazione media

Le tre stampe mostrano rispettivamente:

1. soddisfazione media complessiva;
2. soddisfazione media degli ordini veloci;
3. soddisfazione media degli ordini lenti.


In [22]:
print(soddisfazione_media)
print(soddisfazione_veloci)
print(soddisfazione_lenta)

3.87
4.78
2.8


## 12. Confronto economico tra ordini veloci e lenti

Oltre alla soddisfazione, vengono confrontati anche ricavi e margini medi dei due gruppi.

Questo permette di capire se gli ordini consegnati più rapidamente sono anche più interessanti dal punto di vista economico.


In [23]:
ricavo_medio_veloci = np.round(np.mean(ricavo[consegna_veloce]),2)
ricavo_medio_lenti = np.round(np.mean(ricavo[consegna_lenta]),2)
margine_medio_veloci = np.round(np.mean(margine[consegna_veloce]),2)
margine_medio_lenti = np.round(np.mean(margine[consegna_lenta]),2)

### Output del confronto economico

Le stampe mostrano ricavo medio e margine medio per ordini veloci e lenti.


In [24]:
print(ricavo_medio_veloci)
print(ricavo_medio_lenti)
print(margine_medio_veloci)
print(margine_medio_lenti)

163.56
289.3
65.78
91.1


## 13. Confronto del margine percentuale medio

Il confronto viene completato analizzando il margine percentuale medio per ordini veloci e ordini lenti.

Questa metrica è utile perché normalizza la redditività rispetto al valore dell'ordine.


In [25]:
margine_percentuale_medio_veloci = np.round(np.mean(margine_percentuale[consegna_veloce]),2)
margine_percentuale_medio_lenti = np.round(np.mean(margine_percentuale[consegna_lenta]),2)

### Output del margine percentuale medio per segmento

Le due stampe confrontano la redditività relativa degli ordini veloci e lenti.


In [26]:
print(margine_percentuale_medio_veloci)
print(margine_percentuale_medio_lenti)

40.89
34.91


## 14. Costruzione del Quality Score

Il `quality_score` è un indicatore sintetico creato per valutare ogni ordine combinando tre dimensioni:

- margine percentuale;
- soddisfazione cliente;
- giorni di consegna.

La formula premia gli ordini redditizi e con alta soddisfazione, penalizzando invece i tempi di consegna più lunghi.

$$
	ext{Quality Score} = 	ext{Margine percentuale} + (	ext{Soddisfazione} 	imes 10) - (	ext{Giorni consegna} 	imes 2)
$$


In [27]:
quality_score = np.round(margine_percentuale + soddisfazione * 10 - giorni_consegna * 2,2)

### Indicatori descrittivi del Quality Score

Vengono calcolati valore medio, massimo e minimo del `quality_score`.


In [28]:
quality_score_medio = np.round(np.mean(quality_score),2)
quality_score_massimo = np.round(np.max(quality_score),2)
quality_score_minimo = np.round(np.min(quality_score),2)

### Stampa del Quality Score

La prima stampa mostra il punteggio di ogni ordine.  
Le stampe successive mostrano media, massimo e minimo.


In [29]:
print(quality_score)
print(quality_score_medio)
print(quality_score_massimo)
print(quality_score_minimo)

[84.   63.33 91.   56.   62.   48.   88.86 74.   44.   70.   73.67 56.89
 88.44 34.   76.   75.33 57.5  56.57 80.36 73.82 46.44 56.84 75.33 58.
 56.91 78.62 72.   90.74 32.33 64.38]
66.18
91.0
32.33


## 15. Selezione degli ordini con Quality Score elevato

Vengono selezionati gli ordini con `quality_score` maggiore o uguale a 80.

Questa soglia identifica gli ordini considerati migliori secondo il criterio sintetico definito.


In [30]:
maschera_qualità = quality_score >= 80
ordini_migliori_quality = dataset[maschera_qualità]
quality_alti = quality_score[maschera_qualità]

### Stampa degli ordini migliori per Quality Score

La prima stampa mostra le righe del dataset.  
La seconda stampa mostra i relativi punteggi.


In [31]:
print(ordini_migliori_quality)
print(quality_alti)

[[  2  50  30   3   5]
 [  3  40  22   2   5]
 [  4  35  20   2   5]
 [  4  45  25   3   5]
 [  2 110  70   3   5]
 [  4  38  21   2   5]]
[84.   91.   88.86 88.44 80.36 90.74]


## 16. Miglior ordine secondo il Quality Score

Con `np.argmax()` viene individuato l'indice dell'ordine con il punteggio più alto.

> **Nota:** da questo punto in poi la variabile `ordine_migliore` si riferisce al miglior ordine secondo il `quality_score`, non più al margine economico assoluto calcolato nelle prime sezioni.


In [32]:
indice_migliore = np.argmax(quality_score)
ordine_migliore = dataset[indice_migliore]
quality_migliore = quality_score[indice_migliore]

### Output del miglior ordine

Vengono stampati l'ordine migliore e il relativo `quality_score`.


In [33]:
print(ordine_migliore)
print(quality_migliore)

[ 3 40 22  2  5]
91.0


## 17. Peggior ordine secondo il Quality Score

Con `np.argmin()` viene individuato l'indice dell'ordine con il punteggio più basso.


In [34]:
indice_peggiore = np.argmin(quality_score)
ordine_peggiore = dataset[indice_peggiore]
quality_peggiore = quality_score[indice_peggiore]

### Output del peggior ordine

Vengono stampati l'ordine peggiore e il relativo `quality_score`.


In [35]:
print(ordine_peggiore)
print(quality_peggiore)

[  1 600 430   8   2]
32.33


## 18. Classificazione qualitativa degli ordini

Gli ordini vengono classificati in tre categorie:

| Classe | Condizione |
|---|---|
| `Eccellente` | `quality_score >= 80` |
| `Buona` | `quality_score >= 60` e inferiore a 80 |
| `Critico` | `quality_score < 60` |

La funzione `np.where()` permette di creare una classificazione condizionale vettorializzata.


In [36]:
classe_quality = np.where(quality_score >= 80, "Eccellente",
                 np.where(quality_score >= 60, "Buona", "Critico"))
print(classe_quality)

['Eccellente' 'Buona' 'Eccellente' 'Critico' 'Buona' 'Critico'
 'Eccellente' 'Buona' 'Critico' 'Buona' 'Buona' 'Critico' 'Eccellente'
 'Critico' 'Buona' 'Buona' 'Critico' 'Critico' 'Eccellente' 'Buona'
 'Critico' 'Critico' 'Buona' 'Critico' 'Critico' 'Buona' 'Buona'
 'Eccellente' 'Critico' 'Buona']


## 19. Conteggio delle classi qualitative

Viene calcolato il numero di ordini appartenenti a ciascuna categoria.


In [37]:
ordini_eccellenti = np.sum(classe_quality == "Eccellente")
ordini_buoni = np.sum(classe_quality == "Buona")
ordini_critici = np.sum(classe_quality == "Critico")

### Output del conteggio classi

Queste stampe mostrano quanti ordini sono classificati come eccellenti, buoni o critici.


In [38]:
print(ordini_eccellenti)
print(ordini_buoni)
print(ordini_critici)

6
12
12


## 20. Distribuzione percentuale delle classi

Con `np.unique()` vengono recuperate le classi presenti e il rispettivo numero di occorrenze.  
Successivamente viene calcolata la percentuale di ogni classe sul totale degli ordini.


In [39]:
classi, conteggi = np.unique(classe_quality, return_counts=True)
percentuali_ordini = np.round(conteggi / numero_ordini * 100,2)
print(classi)
print(conteggi)
print(percentuali_ordini)

['Buona' 'Critico' 'Eccellente']
[12 12  6]
[40. 40. 20.]


## 21. Tabella riepilogativa classi

I conteggi e le percentuali vengono uniti in un'unica struttura tramite `np.column_stack()`.


In [40]:
riepilogativo = np.column_stack((conteggi, percentuali_ordini))
print(riepilogativo)

[[12. 40.]
 [12. 40.]
 [ 6. 20.]]


## 22. Ordinamento delle classi per frequenza

Le classi vengono ordinate in base al numero di ordini, dalla più frequente alla meno frequente.

Questo passaggio rende più immediata la lettura della distribuzione qualitativa.


In [41]:
indici_ordinati = np.argsort(conteggi)[::-1]
classi_ordinati = classi[indici_ordinati]
conteggi_ordinati = conteggi[indici_ordinati]
percentuali_ordinati = percentuali_ordini[indici_ordinati]

### Output delle classi ordinate

Vengono stampati gli indici ordinati, le classi, i conteggi e le percentuali ordinate.


In [42]:
print(indici_ordinati)
print(classi_ordinati)
print(conteggi_ordinati)
print(percentuali_ordinati)

[1 0 2]
['Critico' 'Buona' 'Eccellente']
[12 12  6]
[40. 40. 20.]


## 23. Report finale

L'ultima sezione sintetizza i principali risultati dell'analisi in un formato leggibile.

Il report include:

- ricavi, costi e margini totali;
- margine percentuale medio;
- soddisfazione media;
- numero di ordini eccellenti e critici;
- miglior e peggior ordine secondo il `quality_score`.


In [43]:
print("REPORT FINALE ANALISI ORDINI")
print("-----------------------------")

print(f"Ricavo totale: {ricavo_totale}")
print(f"Costo totale: {costo_totale}")
print(f"Margine totale: {margine_totale}")
print(f"Margine percentuale medio: {margine_percentuale_medio}")
print(f"Soddisfazione media: {soddisfazione_media}")

print(f"Ordini eccellenti: {ordini_eccellenti}")
print(f"Ordini critici: {ordini_critici}")

print(f"Miglior ordine: {ordine_migliore}")
print(f"Quality score miglior ordine: {quality_migliore}")

print(f"Peggior ordine: {ordine_peggiore}")
print(f"Quality score peggior ordine: {quality_peggiore}")

REPORT FINALE ANALISI ORDINI
-----------------------------
Ricavo totale: 7500
Costo totale: 4911
Margine totale: 2589
Margine percentuale medio: 36.98
Soddisfazione media: 3.87
Ordini eccellenti: 6
Ordini critici: 12
Miglior ordine: [ 3 40 22  2  5]
Quality score miglior ordine: 91.0
Peggior ordine: [  1 600 430   8   2]
Quality score peggior ordine: 32.33


---

## Osservazioni finali

Il progetto dimostra in modo efficace l'utilizzo di NumPy per:

- creare e manipolare array;
- selezionare colonne e righe;
- costruire maschere booleane;
- calcolare indicatori aggregati;
- classificare osservazioni tramite condizioni;
- costruire un report sintetico finale.